' Parametric leaf antenna generator for CST Studio Suite 2025
' Units: mm, GHz
'
' Usage:
'   1. Open a new CST Microwave Studio project.
'   2. Macro > Visual Basic > Open this file > Run.
'   3. Tune parameters in CST's parameter list, then rerun this macro to rebuild.
'
' Main sweep parameter:
'   num_fin_pairs      Number of fins. In alternating mode this is individual fins; in mirrored mode this is fin pairs.
'
' Useful tuning parameters:
'   leaf_length        Tip-to-base leaf length.
'   leaf_height        Maximum leaf width.
'   rim_width          Width of the outer leaf rim.
'   metal_thickness    Copper thickness, default 1 mm from the drawing.
'   center_stem_width  Width of the center conductor/stem.
'   fin_layout_mode    1 = center-out mirrored fin pairs, 0 = legacy evenly spaced mirrored fin pairs.
'   fin_len_1..8       Individual fin/vein lengths.
'   fin_angle_1..8     Individual fin/vein angles in degrees from +X.
'   fin_end_angle      Slanted cap angle at each fin end.
'   fin_end_len        Length of the slanted cap at each fin end.
'   leaf_base_spline_gap    Centerline gap where the rim starts at the feed/stem side.
'   rim_tip_to_tip_length Vertical distance between the two rim/spline tips.
'   rim_over_stem     How far the upper rim tip extends past the main stem.
'   rim_end_gap        Clear gap between rim inner edges at the opposite end.
'   rim_curve_bias     Shape exponent for the native CST rim spline arc.
'   rim_stem_clearance      Extra clearance between the center stem and outer rim starts.
'   rim_spline_points  Number of points used to define each native CST rim spline.
'   unite_radiator_all Boolean-unite all radiator solids at the end; ground remains separate.
'   trim_fin_stem_overlap Trim fin/vein overlap volume using the main stem as a mask.
'   trim_rim_stem_overlap Trim outer rim/spline overlap volume using the main stem as a mask.
'   trim_rim_feed_overlap Trim outer rim/spline overlap volume using the feed as a mask.
'   vein_rim_clearance Extra clearance from fin/vein ends to the inner rim.
'   vein_stem_overlap  Electrical/mechanical overlap between each vein and the main stem.
'   ground_size        Square ground-plane side length.
'   leaf_ground_gap    Air gap between radiator/feed bottom and ground top.
'   use_tetrahedral_mesh Use tetra/surface-style mesh display instead of forcing PBA mesh planes.
'
' Assumptions in this first model:
'   - The leaf radiator is a 1 mm thick copper solid standing upright in the YZ plane.
'   - The 60 x 60 mm ground plane is horizontal in the XY plane below the feed end.
'   - The SMA is represented as a 50 ohm discrete port from feed to ground.
'   - Geometry is made from short copper brick segments so vein count can be
'     regenerated by the macro without relying on imported DXF topology.

Option Explicit

Const PI As Double = 3.1415926535897931
Dim RadiatorObjects As String
Dim FinObjects As String
Dim RimObjects As String

Sub Main()
    InitProject
    EnsureParameters
    If CInt(P("use_dxf_defaults")) <> 0 Then ApplyDxfDefaults
    RebuildLeafAntenna
    SetupSimulation
End Sub

Sub InitProject()
    With Units
        .Geometry "mm"
        .Frequency "GHz"
        .Time "ns"
    End With

    On Error Resume Next
    Component.Delete "Radiator"
    Component.Delete "Ground"
    Component.Delete "TrimMasks"
    On Error GoTo 0

    Component.New "Radiator"
    Component.New "Ground"
    DefineCopperAnnealed
End Sub

Sub EnsureParameters()
    EnsureParameter "use_dxf_defaults", "1"
    EnsureParameter "freq_min", "2.2"
    EnsureParameter "freq_max", "2.7"
    EnsureParameter "freq_target", "2.45"
    EnsureParameter "debug_rim_only", "0"

    EnsureParameter "total_length", "132.06"
    EnsureParameter "leaf_length", "75.75"
    EnsureParameter "leaf_height", "63.47"
    EnsureParameter "leaf_shape_power", "0.72"
    EnsureParameter "rim_width", "4.2"
    EnsureParameter "leaf_base_spline_gap", "0.0"
    EnsureParameter "rim_tip_to_tip_length", "74.7"
    EnsureParameter "rim_over_stem", "7.0"
    EnsureParameter "rim_end_gap", "2.8"
    EnsureParameter "rim_curve_bias", "0.72"
    EnsureParameter "rim_stem_clearance", "0.2"
    EnsureParameter "rim_spline_points", "9"
    EnsureParameter "unite_radiator_all", "1"
    EnsureParameter "trim_fin_stem_overlap", "1"
    EnsureParameter "trim_rim_stem_overlap", "1"
    EnsureParameter "trim_rim_feed_overlap", "1"
    EnsureParameter "trim_mask_margin", "0.05"
    EnsureParameter "metal_thickness", "1.0"
    EnsureParameter "center_stem_width", "4.2"
    EnsureParameter "feed_width", "3.05"

    EnsureParameter "num_fin_pairs", "4"
    EnsureParameter "fin_layout_mode", "1"
    EnsureParameter "use_fin_angles", "0"
    EnsureParameter "manual_fin_positions", "0"
    EnsureParameter "alternating_fin_center_x", "39.66"
    EnsureParameter "alternating_fin_spacing", "9.91"
    EnsureParameter "fin_start_x", "14.47"
    EnsureParameter "fin_end_x", "56.45"
    EnsureParameter "fin_width", "1.4"
    EnsureParameter "central_fin_width", "4.2"
    EnsureParameter "fin_end_len", "0.0"
    EnsureParameter "fin_end_angle", "0.0"
    EnsureParameter "vein_rim_clearance", "1.0"
    EnsureParameter "vein_stem_overlap", "0.5"

    EnsureParameter "fin_x_1", "14.47"
    EnsureParameter "fin_x_2", "28.82"
    EnsureParameter "fin_x_3", "39.66"
    EnsureParameter "fin_x_4", "56.45"
    EnsureParameter "fin_x_5", "61.0"
    EnsureParameter "fin_x_6", "64.0"
    EnsureParameter "fin_x_7", "67.0"
    EnsureParameter "fin_x_8", "70.0"

    EnsureParameter "fin_len_1", "15.0"
    EnsureParameter "fin_len_2", "10.9"
    EnsureParameter "fin_len_3", "15.0"
    EnsureParameter "fin_len_4", "8.0"
    EnsureParameter "fin_len_5", "16.0"
    EnsureParameter "fin_len_6", "14.0"
    EnsureParameter "fin_len_7", "12.0"
    EnsureParameter "fin_len_8", "10.0"

    EnsureParameter "fin_angle_1", "90.0"
    EnsureParameter "fin_angle_2", "90.0"
    EnsureParameter "fin_angle_3", "90.0"
    EnsureParameter "fin_angle_4", "90.0"
    EnsureParameter "fin_angle_5", "90.0"
    EnsureParameter "fin_angle_6", "90.0"
    EnsureParameter "fin_angle_7", "90.0"
    EnsureParameter "fin_angle_8", "90.0"

    EnsureParameter "segment_overlap", "0.75"

    EnsureParameter "ground_size", "60.0"
    EnsureParameter "leaf_ground_gap", "5.0"
    EnsureParameter "port_impedance", "50.0"
    EnsureParameter "use_tetrahedral_mesh", "1"
End Sub

Sub ApplyDxfDefaults()
    StoreParameter "total_length", "132.06"
    StoreParameter "freq_min", "2.2"
    StoreParameter "freq_max", "2.7"
    StoreParameter "debug_rim_only", "0"
    StoreParameter "leaf_length", "75.75"
    StoreParameter "leaf_height", "63.47"
    StoreParameter "leaf_shape_power", "0.72"
    StoreParameter "rim_width", "4.2"
    StoreParameter "leaf_base_spline_gap", "0.0"
    StoreParameter "rim_tip_to_tip_length", "74.7"
    StoreParameter "rim_over_stem", "7.0"
    StoreParameter "rim_end_gap", "2.8"
    StoreParameter "rim_curve_bias", "0.72"
    StoreParameter "rim_stem_clearance", "0.2"
    StoreParameter "rim_spline_points", "9"
    StoreParameter "unite_radiator_all", "1"
    StoreParameter "trim_fin_stem_overlap", "1"
    StoreParameter "trim_rim_stem_overlap", "1"
    StoreParameter "trim_rim_feed_overlap", "1"
    StoreParameter "trim_mask_margin", "0.05"
    StoreParameter "metal_thickness", "1.0"
    StoreParameter "center_stem_width", "4.2"
    StoreParameter "feed_width", "3.05"
    StoreParameter "num_fin_pairs", "4"
    StoreParameter "fin_layout_mode", "1"
    StoreParameter "use_fin_angles", "0"
    StoreParameter "manual_fin_positions", "0"
    StoreParameter "alternating_fin_center_x", "39.66"
    StoreParameter "alternating_fin_spacing", "9.91"
    StoreParameter "fin_start_x", "14.47"
    StoreParameter "fin_end_x", "56.45"
    StoreParameter "fin_width", "1.4"
    StoreParameter "central_fin_width", "4.2"
    StoreParameter "fin_end_len", "0.0"
    StoreParameter "fin_end_angle", "0.0"
    StoreParameter "vein_rim_clearance", "1.0"
    StoreParameter "vein_stem_overlap", "0.5"

    StoreParameter "fin_x_1", "14.47"
    StoreParameter "fin_x_2", "28.82"
    StoreParameter "fin_x_3", "39.66"
    StoreParameter "fin_x_4", "56.45"
    StoreParameter "fin_x_5", "61.0"
    StoreParameter "fin_x_6", "64.0"
    StoreParameter "fin_x_7", "67.0"
    StoreParameter "fin_x_8", "70.0"

    StoreParameter "fin_len_1", "15.0"
    StoreParameter "fin_len_2", "10.9"
    StoreParameter "fin_len_3", "15.0"
    StoreParameter "fin_len_4", "8.0"
    StoreParameter "fin_len_5", "16.0"
    StoreParameter "fin_len_6", "14.0"
    StoreParameter "fin_len_7", "12.0"
    StoreParameter "fin_len_8", "10.0"

    StoreParameter "fin_angle_1", "90.0"
    StoreParameter "fin_angle_2", "90.0"
    StoreParameter "fin_angle_3", "90.0"
    StoreParameter "fin_angle_4", "90.0"
    StoreParameter "fin_angle_5", "90.0"
    StoreParameter "fin_angle_6", "90.0"
    StoreParameter "fin_angle_7", "90.0"
    StoreParameter "fin_angle_8", "90.0"
    StoreParameter "segment_overlap", "0.75"
    StoreParameter "leaf_ground_gap", "5.0"
    StoreParameter "use_tetrahedral_mesh", "1"
End Sub

Sub RebuildLeafAntenna()
    Dim leafLen As Double, leafHeight As Double, rimW As Double, stemW As Double
    Dim totalLen As Double, metalT As Double
    Dim pwr As Double, halfH As Double, baseOffset As Double, baseGap As Double
    Dim rimStartY As Double, rimStemClearance As Double, rimTipX As Double
    Dim rimEndGap As Double
    Dim stemTopX As Double

    RadiatorObjects = ""
    FinObjects = ""
    RimObjects = ""

    leafLen = P("leaf_length")
    leafHeight = P("leaf_height")
    totalLen = P("total_length")
    rimW = P("rim_width")
    stemW = P("center_stem_width")
    metalT = P("metal_thickness")
    pwr = P("leaf_shape_power")
    halfH = leafHeight / 2#
    baseOffset = leafLen
    baseGap = P("leaf_base_spline_gap")
    If baseGap < 0# Then baseGap = 0#
    rimStemClearance = P("rim_stem_clearance")
    If rimStemClearance < 0# Then rimStemClearance = 0#
    rimStartY = baseGap / 2#
    rimTipX = leafLen - P("rim_tip_to_tip_length")
    stemTopX = rimTipX + P("rim_over_stem")
    If stemTopX < 0# Then stemTopX = 0#
    If stemTopX > leafLen Then stemTopX = leafLen
    rimEndGap = P("rim_end_gap")
    If rimEndGap < 0# Then rimEndGap = 0#
    ' Outer rim: native CST spline traces, not segmented brick approximations.
    AddRimTrace "rim_top", "rim_curve_top", "spline_top", 1#, baseOffset, rimTipX, rimStartY, rimEndGap / 2# + rimW / 2#, rimW, metalT
    AddRimTrace "rim_bot", "rim_curve_bot", "spline_bot", -1#, baseOffset, rimTipX, rimStartY, rimEndGap / 2# + rimW / 2#, rimW, metalT

    If CInt(P("debug_rim_only")) <> 0 Then Exit Sub

    ' Center stem stops below the upper rim tip; feed extension starts at the same intersection where the rim starts.
    AddSegment "center_stem", "Radiator", stemTopX, 0#, leafLen, 0#, stemW, metalT
    AddSegment "feed_extension", "Radiator", leafLen, 0#, totalLen, 0#, P("feed_width"), metalT

    AddFinPairs
    If CInt(P("trim_fin_stem_overlap")) <> 0 Then
        TrimFinsWithStemMask stemTopX
    End If
    If CInt(P("trim_rim_stem_overlap")) <> 0 Then
        TrimRimsWithStemMask stemTopX
    End If
    If CInt(P("trim_rim_feed_overlap")) <> 0 Then
        TrimRimsWithFeedMask
    End If

    If CInt(P("unite_radiator_all")) <> 0 Then
        UniteRadiatorAll
    End If
    CleanupTrimMasks
    AddGroundAndPort
End Sub

Sub AddRimTrace(ByVal objName As String, ByVal curveName As String, ByVal splineName As String, ByVal mirrorY As Double, ByVal xStart As Double, ByVal xEnd As Double, ByVal yStart As Double, ByVal yEnd As Double, ByVal width As Double, ByVal thick As Double)
    Dim pointCount As Integer, i As Integer
    Dim t As Double, x As Double, y As Double

    pointCount = CInt(P("rim_spline_points"))
    If pointCount < 3 Then pointCount = 3

    StartVersionStringOverrideMode "2025.0|34.0.1|20240830"
    With Spline
        .Reset
        .Name splineName
        .Curve curveName

        For i = 0 To pointCount - 1
            t = i / (pointCount - 1)
            x = RimCurveX(t, xStart, xEnd)
            y = mirrorY * RimCurveY(t, yStart, yEnd)

            If i = 0 Then
                .Point S(x), S(y)
                .SetInterpolationType "PointInterpolation"
            Else
                .LineTo S(x), S(y)
            End If
        Next i

        .Create
    End With

    With TraceFromCurve
        .Reset
        .Name objName
        .Component "Radiator"
        .Material "Copper_annealed"
        .Curve curveName & ":" & splineName
        .Thickness S(thick)
        .Width S(width)
        .RoundStart "False"
        .RoundEnd "False"
        .DeleteCurve "True"
        .GapType "2"
        .Create
    End With
    StopVersionStringOverrideMode

    OrientRadiatorShape objName, "Radiator"
    RememberRadiatorObject objName, "Radiator"
    RememberRimObject objName
End Sub

Sub AddLineTrace(ByVal objName As String, ByVal x1 As Double, ByVal y1 As Double, ByVal x2 As Double, ByVal y2 As Double, ByVal width As Double, ByVal thick As Double)
    Dim curveName As String, splineName As String
    Dim xm As Double, ym As Double

    If Sqr((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1)) <= 0.000001 Then Exit Sub

    curveName = objName & "_curve"
    splineName = objName & "_spline"
    xm = (x1 + x2) / 2#
    ym = (y1 + y2) / 2#

    StartVersionStringOverrideMode "2025.0|34.0.1|20240830"
    With Spline
        .Reset
        .Name splineName
        .Curve curveName
        .Point S(x1), S(y1)
        .SetInterpolationType "PointInterpolation"
        .LineTo S(xm), S(ym)
        .LineTo S(x2), S(y2)
        .Create
    End With

    With TraceFromCurve
        .Reset
        .Name objName
        .Component "Radiator"
        .Material "Copper_annealed"
        .Curve curveName & ":" & splineName
        .Thickness S(thick)
        .Width S(width)
        .RoundStart "False"
        .RoundEnd "False"
        .DeleteCurve "True"
        .GapType "2"
        .Create
    End With
    StopVersionStringOverrideMode

    OrientRadiatorShape objName, "Radiator"
    RememberRadiatorObject objName, "Radiator"
End Sub

Sub AddFinPairs()
    Dim pairCount As Integer, maxPairs As Integer, i As Integer
    Dim startX As Double, endX As Double, x0 As Double
    Dim lenV As Double, ang As Double, w As Double, capLen As Double, capAng As Double
    Dim xTop1 As Double, yTop1 As Double, xTop2 As Double, yTop2 As Double
    Dim xBot1 As Double, yBot1 As Double, xBot2 As Double, yBot2 As Double
    Dim spacing As Double, rimClearance As Double, stemOverlap As Double
    Dim stemStartLen As Double, maxLen As Double, visibleLen As Double

    If CInt(P("fin_layout_mode")) <> 0 Then
        AddCenterOutMirroredFins
        Exit Sub
    End If

    pairCount = CInt(P("num_fin_pairs"))
    maxPairs = 8
    If pairCount < 0 Then pairCount = 0
    If pairCount > maxPairs Then pairCount = maxPairs

    startX = P("fin_start_x")
    endX = P("fin_end_x")
    w = P("fin_width")
    capLen = P("fin_end_len")
    capAng = P("fin_end_angle")
    rimClearance = P("rim_width") / 2# + w / 2# + P("vein_rim_clearance") + capLen / 2#
    stemOverlap = P("vein_stem_overlap")

    If pairCount = 1 Then
        spacing = 0#
    Else
        spacing = (endX - startX) / (pairCount - 1)
    End If

    For i = 1 To pairCount
        If CInt(P("manual_fin_positions")) <> 0 Then
            x0 = P("fin_x_" & CStr(i))
        Else
            x0 = startX + spacing * (i - 1)
        End If
        lenV = P("fin_len_" & CStr(i))
        ang = EffectiveFinAngle(i)
        If Abs(Sin(ang)) > 0.000001 Then
            stemStartLen = -stemOverlap
            maxLen = LimitedFinLength(x0, ang, lenV, rimClearance)
            visibleLen = maxLen - stemStartLen

            If visibleLen > 0.25 Then
                xTop1 = x0 + stemStartLen * Cos(ang)
                yTop1 = stemStartLen * Sin(ang)
                xTop2 = x0 + maxLen * Cos(ang)
                yTop2 = maxLen * Sin(ang)
                xBot1 = xTop1
                yBot1 = -yTop1
                xBot2 = xTop2
                yBot2 = -yTop2

                AddSegment "fin_top_" & CStr(i), "Radiator", xTop1, yTop1, xTop2, yTop2, w, P("metal_thickness")
                AddSegment "fin_bot_" & CStr(i), "Radiator", xBot1, yBot1, xBot2, yBot2, w, P("metal_thickness")
                RememberFinObject "fin_top_" & CStr(i)
                RememberFinObject "fin_bot_" & CStr(i)

                AddFinCap "fin_top_cap_" & CStr(i), xTop2, yTop2, ang + capAng * PI / 180#, capLen, w
                AddFinCap "fin_bot_cap_" & CStr(i), xBot2, yBot2, -(ang + capAng * PI / 180#), capLen, w
            End If
        End If
    Next i
End Sub

Sub AddCenterOutMirroredFins()
    Dim pairCount As Integer, maxPairs As Integer, i As Integer
    Dim x0 As Double, lenV As Double, ang As Double
    Dim w As Double, capLen As Double, capAng As Double
    Dim rimClearance As Double, stemOverlap As Double

    pairCount = CInt(P("num_fin_pairs"))
    maxPairs = 8
    If pairCount < 0 Then pairCount = 0
    If pairCount > maxPairs Then pairCount = maxPairs

    capLen = P("fin_end_len")
    capAng = P("fin_end_angle") * PI / 180#
    stemOverlap = P("vein_stem_overlap")

    For i = 1 To pairCount
        w = FinWidthForIndex(i)
        rimClearance = P("rim_width") / 2# + w / 2# + P("vein_rim_clearance") + capLen / 2#

        If CInt(P("manual_fin_positions")) <> 0 Then
            x0 = P("fin_x_" & CStr(i))
        Else
            x0 = AlternatingFinX(i)
        End If

        lenV = P("fin_len_" & CStr(i))
        ang = EffectiveFinAngle(i)

        AddSingleFin "fin_top_" & CStr(i), x0, lenV, ang, 1#, w, rimClearance, stemOverlap, capLen, capAng
        AddSingleFin "fin_bot_" & CStr(i), x0, lenV, ang, -1#, w, rimClearance, stemOverlap, capLen, capAng
    Next i
End Sub

Sub AddSingleFin(ByVal objName As String, ByVal x0 As Double, ByVal lenV As Double, ByVal ang As Double, ByVal side As Double, ByVal w As Double, ByVal rimClearance As Double, ByVal stemOverlap As Double, ByVal capLen As Double, ByVal capAng As Double)
    Dim actualAng As Double
    Dim stemStartLen As Double, maxLen As Double, visibleLen As Double
    Dim x1 As Double, y1 As Double, x2 As Double, y2 As Double

    actualAng = side * ang
    If Abs(Sin(actualAng)) <= 0.000001 Then Exit Sub

    stemStartLen = -stemOverlap
    maxLen = LimitedFinLength(x0, actualAng, lenV, rimClearance)
    visibleLen = maxLen - stemStartLen

    If visibleLen <= 0.25 Then Exit Sub

    x1 = x0 + stemStartLen * Cos(actualAng)
    y1 = stemStartLen * Sin(actualAng)
    x2 = x0 + maxLen * Cos(actualAng)
    y2 = maxLen * Sin(actualAng)

    AddSegment objName, "Radiator", x1, y1, x2, y2, w, P("metal_thickness")
    RememberFinObject objName
    AddFinCap objName & "_cap", x2, y2, actualAng + side * capAng, capLen, w
End Sub

Function AlternatingFinX(ByVal finIndex As Integer) As Double
    Dim centerX As Double, spacing As Double, offsetIndex As Integer
    Dim direction As Double, xVal As Double

    centerX = P("alternating_fin_center_x")
    spacing = P("alternating_fin_spacing")
    If spacing < 0# Then spacing = -spacing

    If finIndex <= 1 Then
        xVal = centerX
    Else
        offsetIndex = finIndex \ 2
        If finIndex Mod 2 = 0 Then
            direction = 1#
        Else
            direction = -1#
        End If
        xVal = centerX + direction * spacing * offsetIndex
    End If

    If xVal < P("fin_start_x") Then xVal = P("fin_start_x")
    If xVal > P("fin_end_x") Then xVal = P("fin_end_x")
    AlternatingFinX = xVal
End Function

Function FinWidthForIndex(ByVal finIndex As Integer) As Double
    If CInt(P("fin_layout_mode")) <> 0 And finIndex = 1 Then
        FinWidthForIndex = P("central_fin_width")
    Else
        FinWidthForIndex = P("fin_width")
    End If
End Function

Function EffectiveFinAngle(ByVal finIndex As Integer) As Double
    If CInt(P("use_fin_angles")) <> 0 Then
        EffectiveFinAngle = P("fin_angle_" & CStr(finIndex)) * PI / 180#
    Else
        EffectiveFinAngle = PI / 2#
    End If
End Function

Sub AddFinCap(ByVal objName As String, ByVal x0 As Double, ByVal y0 As Double, ByVal ang As Double, ByVal capLen As Double, ByVal w As Double)
    Dim x1 As Double, y1 As Double, x2 As Double, y2 As Double

    If capLen <= 0.000001 Then Exit Sub

    x1 = x0 - 0.5 * capLen * Cos(ang)
    y1 = y0 - 0.5 * capLen * Sin(ang)
    x2 = x0 + 0.5 * capLen * Cos(ang)
    y2 = y0 + 0.5 * capLen * Sin(ang)
    AddSegment objName, "Radiator", x1, y1, x2, y2, w, P("metal_thickness")
End Sub

Sub RememberFinObject(ByVal objName As String)
    If FinObjects = "" Then
        FinObjects = objName
    Else
        FinObjects = FinObjects & "|" & objName
    End If
End Sub

Sub RememberRimObject(ByVal objName As String)
    If RimObjects = "" Then
        RimObjects = objName
    Else
        RimObjects = RimObjects & "|" & objName
    End If
End Sub

Sub TrimFinsWithStemMask(ByVal stemStartX As Double)
    Dim names() As String
    Dim i As Integer
    Dim maskName As String

    If FinObjects = "" Then Exit Sub

    On Error Resume Next
    Component.Delete "TrimMasks"
    Component.New "TrimMasks"
    On Error GoTo 0

    names = Split(FinObjects, "|")

    For i = 0 To UBound(names)
        maskName = "stem_trim_mask_" & CStr(i + 1)
        AddStemTrimMask maskName, stemStartX

        On Error Resume Next
        Solid.Subtract "Radiator:" & names(i), "TrimMasks:" & maskName
        Solid.Delete "TrimMasks:" & maskName
        On Error GoTo 0
    Next i

    On Error Resume Next
    Component.Delete "TrimMasks"
    On Error GoTo 0
End Sub

Sub TrimRimsWithStemMask(ByVal stemStartX As Double)
    Dim names() As String
    Dim i As Integer
    Dim maskName As String

    If RimObjects = "" Then Exit Sub

    On Error Resume Next
    Component.Delete "TrimMasks"
    Component.New "TrimMasks"
    On Error GoTo 0

    names = Split(RimObjects, "|")

    For i = 0 To UBound(names)
        maskName = "rim_stem_trim_mask_" & CStr(i + 1)
        AddStemTrimMask maskName, stemStartX

        On Error Resume Next
        Solid.Subtract "Radiator:" & names(i), "TrimMasks:" & maskName
        Solid.Delete "TrimMasks:" & maskName
        On Error GoTo 0
    Next i

    On Error Resume Next
    Component.Delete "TrimMasks"
    On Error GoTo 0
End Sub

Sub TrimRimsWithFeedMask()
    Dim names() As String
    Dim i As Integer
    Dim maskName As String

    If RimObjects = "" Then Exit Sub

    On Error Resume Next
    Component.Delete "TrimMasks"
    Component.New "TrimMasks"
    On Error GoTo 0

    names = Split(RimObjects, "|")

    For i = 0 To UBound(names)
        maskName = "rim_feed_trim_mask_" & CStr(i + 1)
        AddFeedTrimMask maskName

        On Error Resume Next
        Solid.Subtract "Radiator:" & names(i), "TrimMasks:" & maskName
        Solid.Delete "TrimMasks:" & maskName
        On Error GoTo 0
    Next i

    On Error Resume Next
    Component.Delete "TrimMasks"
    On Error GoTo 0
End Sub

Sub AddStemTrimMask(ByVal maskName As String, ByVal stemStartX As Double)
    Dim margin As Double
    Dim stemW As Double

    margin = P("trim_mask_margin")
    If margin < 0# Then margin = 0#
    stemW = P("center_stem_width")

    AddBrick maskName, "TrimMasks", stemStartX - margin, P("leaf_length") + margin, -stemW / 2# - margin, stemW / 2# + margin, -margin, P("metal_thickness") + margin
    OrientRadiatorShape maskName, "TrimMasks"
End Sub

Sub AddFeedTrimMask(ByVal maskName As String)
    Dim margin As Double
    Dim feedW As Double

    margin = P("trim_mask_margin")
    If margin < 0# Then margin = 0#
    feedW = P("feed_width")

    AddBrick maskName, "TrimMasks", P("leaf_length") - margin, P("total_length") + margin, -feedW / 2# - margin, feedW / 2# + margin, -margin, P("metal_thickness") + margin
    OrientRadiatorShape maskName, "TrimMasks"
End Sub

Sub CleanupTrimMasks()
    Dim i As Integer

    On Error Resume Next
    For i = 1 To 16
        Solid.Delete "TrimMasks:stem_trim_mask_" & CStr(i)
        Solid.Delete "TrimMasks:rim_stem_trim_mask_" & CStr(i)
        Solid.Delete "TrimMasks:rim_feed_trim_mask_" & CStr(i)
    Next i
    Component.Delete "TrimMasks"
    On Error GoTo 0
End Sub

Sub RememberRadiatorObject(ByVal objName As String, ByVal compName As String)
    If compName <> "Radiator" Then Exit Sub

    If RadiatorObjects = "" Then
        RadiatorObjects = objName
    Else
        RadiatorObjects = RadiatorObjects & "|" & objName
    End If
End Sub

Sub UniteRadiatorAll()
    Dim names() As String
    Dim baseObj As String
    Dim i As Integer

    If RadiatorObjects = "" Then Exit Sub

    names = Split(RadiatorObjects, "|")
    If UBound(names) < 1 Then Exit Sub

    baseObj = "Radiator:" & names(0)

    On Error Resume Next
    For i = 1 To UBound(names)
        Solid.Add baseObj, "Radiator:" & names(i)
    Next i
    On Error GoTo 0
End Sub

Sub AddGroundAndPort()
    Dim totalLen As Double, gs As Double, gap As Double, t As Double
    Dim x0 As Double, y0 As Double

    totalLen = P("total_length")
    gs = P("ground_size")
    gap = P("leaf_ground_gap")
    t = P("metal_thickness")
    x0 = t / 2#
    y0 = 0#

    AddBrick "ground_plane", "Ground", x0 - gs / 2#, x0 + gs / 2#, y0 - gs / 2#, y0 + gs / 2#, -gap - t, -gap

    With DiscretePort
        .Reset
        .PortNumber "1"
        .Type "SParameter"
        .Impedance S(P("port_impedance"))
        .Voltage "1.0"
        .Current "1.0"
        .SetP1 "False", S(x0), "0", S(-gap)
        .SetP2 "False", S(x0), "0", "0"
        .InvertDirection "False"
        .LocalCoordinates "False"
        .Monitor "True"
        .Create
    End With
End Sub

Sub SetupSimulation()
    With Boundary
        .Xmin "expanded open"
        .Xmax "expanded open"
        .Ymin "expanded open"
        .Ymax "expanded open"
        .Zmin "expanded open"
        .Zmax "expanded open"
        .Xsymmetry "none"
        .Ysymmetry "none"
        .Zsymmetry "none"
    End With

    With Solver
        .FrequencyRange S(P("freq_min")), S(P("freq_max"))
    End With

    ConfigureMeshType

    With Monitor
        .Reset
        .Name "farfield_2p45"
        .Domain "Frequency"
        .FieldType "Farfield"
        .Frequency S(P("freq_target"))
        .Create
    End With

    With Monitor
        .Reset
        .Name "e_field_2p45"
        .Domain "Frequency"
        .FieldType "Efield"
        .Frequency S(P("freq_target"))
        .Create
    End With

    With Monitor
        .Reset
        .Name "h_field_2p45"
        .Domain "Frequency"
        .FieldType "Hfield"
        .Frequency S(P("freq_target"))
        .Create
    End With
End Sub

Sub ConfigureMeshType()
    If CInt(P("use_tetrahedral_mesh")) <> 0 Then
        On Error Resume Next
        With Mesh
            .MeshType "Tetrahedral"
        End With
        If Err.Number <> 0 Then
            Err.Clear
            With Mesh
                .MeshType "Tet"
            End With
        End If
        On Error GoTo 0
    Else
        With Mesh
            .MeshType "PBA"
        End With
    End If
End Sub

Sub AddSegment(ByVal objName As String, ByVal compName As String, ByVal x1 As Double, ByVal y1 As Double, ByVal x2 As Double, ByVal y2 As Double, ByVal width As Double, ByVal thick As Double)
    Dim dx As Double, dy As Double, lenV As Double, cx As Double, cy As Double
    Dim angDeg As Double, ov As Double

    If compName = "Radiator" Then
        AddLineTrace objName, x1, y1, x2, y2, width, thick
        Exit Sub
    End If

    dx = x2 - x1
    dy = y2 - y1
    lenV = Sqr(dx * dx + dy * dy)
    If lenV <= 0.000001 Then Exit Sub

    cx = (x1 + x2) / 2#
    cy = (y1 + y2) / 2#
    angDeg = Atn2Deg(dy, dx)
    ov = P("segment_overlap")

    AddBrick objName, compName, cx - lenV / 2# - ov, cx + lenV / 2# + ov, cy - width / 2#, cy + width / 2#, 0#, thick

    If Abs(angDeg) > 0.000001 Then
        With Transform
            .Reset
            .Name compName & ":" & objName
            .Origin "Free"
            .Center S(cx), S(cy), S(thick / 2#)
            .Angle "0", "0", S(angDeg)
            .MultipleObjects "False"
            .GroupObjects "False"
            .Repetitions "1"
            .MultipleSelection "False"
            .Transform "Shape", "Rotate"
        End With
    End If

    If compName = "Radiator" Then
        OrientRadiatorShape objName, compName
    End If
End Sub

Sub OrientRadiatorShape(ByVal objName As String, ByVal compName As String)
    ' The sketch is generated flat in XY. Rotate it into the vertical YZ plane:
    ' original X becomes height above the ground, original Y stays horizontal,
    ' and original Z becomes the 1 mm copper thickness in X.
    With Transform
        .Reset
        .Name compName & ":" & objName
        .Origin "Free"
        .Center "0", "0", "0"
        .Angle "0", "90", "0"
        .MultipleObjects "False"
        .GroupObjects "False"
        .Repetitions "1"
        .MultipleSelection "False"
        .Transform "Shape", "Rotate"
    End With

    With Transform
        .Reset
        .Name compName & ":" & objName
        .Vector "0", "0", S(P("total_length"))
        .MultipleObjects "False"
        .GroupObjects "False"
        .Repetitions "1"
        .MultipleSelection "False"
        .Transform "Shape", "Translate"
    End With
End Sub

Sub AddBrick(ByVal objName As String, ByVal compName As String, ByVal xmin As Double, ByVal xmax As Double, ByVal ymin As Double, ByVal ymax As Double, ByVal zmin As Double, ByVal zmax As Double)
    With Brick
        .Reset
        .Name objName
        .Component compName
        .Material "Copper_annealed"
        .Xrange S(xmin), S(xmax)
        .Yrange S(ymin), S(ymax)
        .Zrange S(zmin), S(zmax)
        .Create
    End With

    RememberRadiatorObject objName, compName
End Sub

Sub DefineCopperAnnealed()
    On Error Resume Next
    Material.Delete "Copper_annealed"
    On Error GoTo 0

    With Material
        .Reset
        .Name "Copper_annealed"
        .Type "Normal"
        .FrqType "all"
        .Epsilon "1"
        .Mue "1"
        .Kappa "5.8e7"
        .TanD "0"
        .Colour "1", "0.55", "0.12"
        .Create
    End With
End Sub

Sub EnsureParameter(ByVal paramName As String, ByVal defaultValue As String)
    Dim tmp As Double
    On Error Resume Next
    tmp = Evaluate(paramName)
    If Err.Number <> 0 Then
        Err.Clear
        StoreParameter paramName, defaultValue
    End If
    On Error GoTo 0
End Sub

Function P(ByVal paramName As String) As Double
    P = CDbl(Evaluate(paramName))
End Function

Function S(ByVal value As Double) As String
    S = Replace(Trim$(Str$(value)), ",", ".")
End Function

Function MaxD(ByVal a As Double, ByVal b As Double) As Double
    If a >= b Then
        MaxD = a
    Else
        MaxD = b
    End If
End Function

Function LeafHalfWidthAtX(ByVal x As Double) As Double
    Dim leafLen As Double, halfH As Double, pwr As Double, sVal As Double

    leafLen = P("leaf_length")
    halfH = P("leaf_height") / 2#
    pwr = P("leaf_shape_power")

    If x <= 0# Or x >= leafLen Then
        LeafHalfWidthAtX = 0#
    Else
        sVal = Sin(PI * x / leafLen)
        If sVal < 0# Then sVal = 0#
        LeafHalfWidthAtX = halfH * sVal ^ pwr
    End If
End Function

Function RimCurveX(ByVal t As Double, ByVal xStart As Double, ByVal xEnd As Double) As Double
    If t < 0# Then t = 0#
    If t > 1# Then t = 1#
    RimCurveX = xStart + (xEnd - xStart) * t
End Function

Function RimCurveY(ByVal t As Double, ByVal yStart As Double, ByVal yEnd As Double) As Double
    Dim yOuter As Double, shapePower As Double
    Dim baseY As Double, archY As Double

    If t < 0# Then t = 0#
    If t > 1# Then t = 1#

    yOuter = P("leaf_height") / 2#
    shapePower = P("rim_curve_bias")
    If shapePower < 0.25 Then shapePower = 0.25
    If shapePower > 2.5 Then shapePower = 2.5

    ' DXF-like half-sine/ellipse rim: endpoints stay near the stem openings,
    ' while the middle smoothly reaches the maximum leaf half-height.
    baseY = yStart + (yEnd - yStart) * t
    archY = (yOuter - baseY) * (Sin(PI * t) ^ shapePower)
    RimCurveY = baseY + archY
End Function

Function OuterRimHalfWidthAtX(ByVal x As Double) As Double
    Dim baseOffset As Double, baseGap As Double, rimW As Double, stemW As Double
    Dim rimStemClearance As Double, startY As Double, endY As Double
    Dim rimTipX As Double, t As Double

    baseOffset = P("leaf_length")
    baseGap = P("leaf_base_spline_gap")
    rimW = P("rim_width")
    stemW = P("center_stem_width")
    rimStemClearance = P("rim_stem_clearance")

    If baseGap < 0# Then baseGap = 0#
    If rimStemClearance < 0# Then rimStemClearance = 0#

    startY = baseGap / 2#
    endY = P("rim_end_gap") / 2# + rimW / 2#
    rimTipX = P("leaf_length") - P("rim_tip_to_tip_length")

    If x <= rimTipX Then
        OuterRimHalfWidthAtX = endY
    ElseIf x >= baseOffset Then
        OuterRimHalfWidthAtX = startY
    Else
        t = (x - baseOffset) / (rimTipX - baseOffset)
        OuterRimHalfWidthAtX = RimCurveY(t, startY, endY)
    End If
End Function

Function IsInsideLeafInterior(ByVal x As Double, ByVal y As Double, ByVal clearance As Double) As Boolean
    Dim innerHalfWidth As Double
    Dim rimTipX As Double

    rimTipX = P("leaf_length") - P("rim_tip_to_tip_length")
    If x <= rimTipX Or x >= P("leaf_length") Then
        IsInsideLeafInterior = False
        Exit Function
    End If

    innerHalfWidth = OuterRimHalfWidthAtX(x) - clearance
    IsInsideLeafInterior = (innerHalfWidth > 0# And Abs(y) <= innerHalfWidth)
End Function

Function LimitedFinLength(ByVal x0 As Double, ByVal ang As Double, ByVal requestedLen As Double, ByVal clearance As Double) As Double
    Dim hi As Double, lo As Double, mid As Double, i As Integer
    Dim xTest As Double, yTest As Double

    If requestedLen <= 0# Then
        LimitedFinLength = 0#
        Exit Function
    End If

    lo = 0#
    hi = requestedLen
    xTest = x0 + hi * Cos(ang)
    yTest = hi * Sin(ang)

    If IsInsideLeafInterior(xTest, yTest, clearance) Then
        LimitedFinLength = hi
        Exit Function
    End If

    For i = 1 To 36
        mid = (lo + hi) / 2#
        xTest = x0 + mid * Cos(ang)
        yTest = mid * Sin(ang)
        If IsInsideLeafInterior(xTest, yTest, clearance) Then
            lo = mid
        Else
            hi = mid
        End If
    Next i

    LimitedFinLength = lo
End Function

Function Atn2Deg(ByVal y As Double, ByVal x As Double) As Double
    If Abs(x) < 0.000000000001 Then
        If y >= 0# Then
            Atn2Deg = 90#
        Else
            Atn2Deg = -90#
        End If
    Else
        Atn2Deg = Atn(y / x) * 180# / PI
        If x < 0# Then
            If y >= 0# Then
                Atn2Deg = Atn2Deg + 180#
            Else
                Atn2Deg = Atn2Deg - 180#
            End If
        End If
    End If
End Function
